# -*- coding: utf-8 -*-
"""reddit_ai_bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mmnQoVu4sd535kAOyVAqCP-NwAoyCDZY
"""

!pip install praw
!pip install openai

import praw

reddit = praw.Reddit(
    client_id='cEnNHKkfeEhnKpB-BCWnWg',
    client_secret='midPmtoH4ByTgpX6IBC8JZ_ESiTp7Q',
    username='Proud-xyz',
    password='Password',
    user_agent='AI Bot for Reddit'
)
# Test the connection by printing the 5 hottest posts from a subreddit
subreddit = reddit.subreddit('learnpython')
for post in subreddit.hot(limit=5):
    print(f"Title: {post.title}, Upvotes: {post.score}")

import openai

# Set up OpenAI API key
openai.api_key = 'xyz'

def generate_ai_response(comment_text):
    response = openai.Completion.create(
        engine="text-davinci-003",
        prompt=f"Reply to this Reddit comment: {comment_text}",
        max_tokens=150,
        temperature=0.7
    )
    return response.choices[0].text.strip()

def like_and_repost_comment(comment):
    if comment.score > 10:  # Example condition: like comments with more than 10 upvotes
        comment.upvote()
        comment.reply("This is a great comment! Sharing it for more visibility.")

def promote_product(comment_text):
    if 'recommend' in comment_text.lower():
        return "Have you tried using ProductX? It's a great tool for your needs!"

